package entitydao;

import java.io.*;

import entity.Order;

/**
 * Data access object for <code>Order.csv</code> file
 * */
public class OrderDAO {

    /**
     * Get the order that was inserted earlier by the passenger. <p>Because there can only exist one order per person on one flight,
     * There is no need to use <code>JsonArray</code> object as in <code>BookingDAO</code>. Instead, the extracted <code>Order</code> object was returned.
     *
     * @param idnum  One of the 2 keys
     * @param flightNo  Another key
     * @return The extracted <code>Order</code> object
     * */
    public Order getOrder(String idnum, String flightNo) {
        
        Order odr = new Order();
        String line = "";
        String splitBy = ",";
        try {
            BufferedReader bf = new BufferedReader(new FileReader("./src/main/resources/Order.csv"));
            while ((line = bf.readLine()) != null) {
                String[] eachline = line.split(splitBy);
                if (eachline[0].equals(idnum) && eachline[1].equals(flightNo)) {
                    odr.setIdnum(eachline[0]);
                    odr.setFlightNo(eachline[1]);
                    odr.setFlightDate(eachline[2]);
                    odr.setSeatno(eachline[3]);
                    odr.setFoodType(eachline[4]);
                    odr.setFoodMenu(eachline[5]);
                    odr.setDrink(eachline[6]);
                    odr.setNote(eachline[7]);

                    break;
                }
            }
            bf.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return odr;
    }

    /**
     * Insert the order that was generated by passenger in the check in work routine
     *
     * @param odr  The<code>Order</code> object to be inserted into <code>Order.csv</code> file
     * */
    public void insertOrder(Order odr) {

        StringBuilder sb = new StringBuilder();
        sb.append(odr.getIdnum());
        sb.append(","+odr.getFlightNo());
        sb.append(","+odr.getFlightDate());
        sb.append(","+odr.getSeatno());
        sb.append(","+odr.getFoodType());
        sb.append(","+odr.getFoodMenu());
        sb.append(","+odr.getDrink());
        sb.append(","+odr.getNote());

        PrintWriter out = null;
        try {
            out = new PrintWriter(new BufferedWriter(new FileWriter("./src/main/resources/Order.csv", true)));
            out.println(sb);
        }catch (IOException e) {
            System.err.println(e);
        }finally{
            if(out != null){
                out.close();
            }
        }
    }

}
