package uiutility;

import entity.Flight;
import entity.Order;
import entity.Passenger;
import entitydao.FlightDAO;
import entitydao.PassengerDAO;

import java.io.*;

/**
 * A class to generate boarding pass, counter number and luggage tag according to the <code>Order</code> made by passenger
 * through the check in process.
 * */
public class GenerationCtrl {

    /**
     * Generates the boarding pass and counter number, output as a .txt file
     *
     * @param odr  The <code>Order</code> generated by the passenger
     * */
    public void printBoardingPassAndCounterNumber(Order odr) {
        try {
            Passenger psgr = new PassengerDAO().getPsgr(odr.getIdnum());
            Flight flight = new FlightDAO().getFlight(odr.getFlightNo());
            String filename = "./boarding_pass/" + psgr.getName() +"_"+ flight.getFlightno() + ".txt";
            File file = new File(filename);
            file.createNewFile();
            FileWriter out = new FileWriter(file);
            out.write("--------------------------------------------------------------\n");
            out.write("Your name: " + psgr.getName() + "\n");
            out.write("Flight number & destination: " + flight.getFlightno() + ", " + flight.getDest() + "\n");
            out.write("Flight date & time: " + flight.getFlightDate() + "," + flight.getTakeoffTime() + "\n");
            out.write("Counter number: " + (int)(50 * Math.random() + 1) + "\n");
            out.write("GOODBYE" + "\n");
            out.write("--------------------------------------------------------------\n");
            out.close();
        } catch (IOException e) {
           e.printStackTrace();
        }
    }

    /**
     * Generates the luggage tag, output as a .txt file
     *
     * @param odr  The <code>Order</code> generated by the passenger
     * */
    public void printLuggageTag(Order odr) {
        try {
            Passenger psgr = new PassengerDAO().getPsgr(odr.getIdnum());
            Flight flight = new FlightDAO().getFlight(odr.getFlightNo());
            String filename = "./luggage_tag/LuGGageTAg" +"_"+ psgr.getName() +"_"+ flight.getFlightno() + ".txt";
            File file = new File(filename);
            file.createNewFile();
            FileWriter out = new FileWriter(file);
            out.write("--------------------------------------------------------------\n");
            out.write("Name: " + psgr.getName() + "\n");
            out.write("Flight number & destination: " + flight.getFlightno() + ", " + flight.getDest() + "\n");
            out.write("Flight date & time: " + flight.getFlightDate() + "," + flight.getTakeoffTime() + "\n");
            out.write("Luggage No: " + (50 * Math.random() + 1) + "\n");
            out.write("----------------------------------------------------------------\n");
            out.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
